import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="business">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
